# AB IoT Testnet config

# AWS KMS
APISignKeyId = "alias/ABConnectSignKey"
ManagerAPISignKeyId = "alias/ABConnectSignKey"
CoreSignKeyId = "alias/ABConnectSignKey"
ToolsSignKeyId = "alias/ABConnectSignKey"

EnableNotify = true


[Pushover]
    Token = "<pushover_token>"
    Key = "<pushover_key>"

[Blockchain]
    Network = "ABIoTTestnet" # blockchainId <==> network + chain
    ChainId = "1007" # ChainId or chain name, get from rpcurl
    BaseChain = "NewChain"
    ChainAPIHost = "127.0.0.1:8602" # the grpc api host
    RPCUrl = "https://rpc.iot.testnet.ab.org"
    DelayBlockNumber = 10 # block number to confirm
    ChainKeyId = "alias/ABConnectKey"
    ChainAPISignKeyId = "alias/ABConnectSignKey"
    ChainTaskSignKeyId = "alias/ABConnectSignKey"
    ChainManagerSignKeyId = "alias/ABConnectSignKey"
    MonitorSignKeyId = "alias/ABConnectSignKey"

[Blockchain.DB]
    adapter = "mysql"
    database = "abconnect_abiot_testnet_accounts"
    host = "127.0.0.1"
    password = "password"
    user = "abconnect_accounts"

[DB]
    adapter = "mysql"
    database = "abconnect"
    host = "127.0.0.1"
    password = "password"
    user = "abconnect"

