dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY} 
  from_key0: ${PRIVATE_KEY}
  from_key1: ${PRIVATE_KEY2}
  from_key2: ${PRIVATE_KEY2}
dependencies:
  # -  <organization/repo>@<version>
  - OpenZeppelin/openzeppelin-contracts@4.6.0
  - smartcontractkit/chainlink-brownie-contracts@0.4.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1'
reports:
    exclude_contracts:
        - ERC721A
        - ERC721ABurnable
        - Index
        - Land
        - HorsePartnerships
        - SilksERC1155Burnable
        - Ownable
        - Pausable